### ISSUE TITLE
In ham radio, this is called "squelch"

### ISSUE THREAD

**Issue by linas** [otalk/hark#18]
A squelch circuit turns off the sound when no one is talking. You'll hear it in police TV shows, when the cops talk to each other over walkie-talkies.

**Comment by xdumaine** [comment]
This is not a descriptive issue.

**Comment by linas** [comment]
? In what way is it not descriptive ? See, for example: https://en.wikipedia.org/wiki/Squelch -- this is the more-or-less standard term used to describe this type of software.  I cannot think of a single word that is more descriptive than this.

If you think that it is not descriptive, can you at least offer a term that is descriptive? "noise suppressor"? "noise limiter?" Some other term?

**Comment by xdumaine** [comment]
What are you asking for? You never asked a question about this library, never described a bug, and never requested a feature. Your issue just describes a noun.

**Comment by linas** [comment]
I'm confused.  What additional information do you wish to have?

**Comment by xdumaine** [comment]
Information for what? Are you asking for us to rename the library?

**Comment by linas** [comment]
I'm asking that the description of the software include some of the standard terminology used to describe what this software does.  By correctly and accurately describing the software, it makes it easier to search on google, and evaluate what it does. 

For example, the README states that "If the power is above a threshold, it's determined to be speech."  But it does not state how it is determined to be speech.  Upon reading further, it does not sound like it is a voice-detector at all, and that instead, it will respond to pops and clicks and rumbles -- its purely responsive to power, on all frequency bands, with no filtering in ether the time or the frequency domain.  In other words, if a car or a truck drives by, it will identify it as a "voice".  

If so, that means that this software provides "squelch" or "noise suppression", rather than actually providing "voice detection".

**Comment by atomicthumbs** [comment]
I agree.

**Comment by xdumaine** [comment]
This library does absolutely no squelching or noise suppression.
