### ISSUE TITLE
Any way we could get a version on npm without example folder

### ISSUE THREAD

**Issue by jpiepkow** [otalk/hark#30]
Adding 2 mb to a lib just for an example seems kind of crazy. The lib otherwise would be well under 50kb and seems much preferable to 2mb.

**Comment by fippo** [comment]
done in 914594d9358df1af39317a8580469b780a2dfb8d and published as 1.1.6 -- @latentflip had already added a npmignore but it was a bit too restrictive

**Comment by xdumaine** [comment]
🎉 thanks @fippo
