### ISSUE TITLE
Some incoming deprecations

### ISSUE THREAD

**Issue by ibc** [otalk/hark#33]
In Chromium 62:

> [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
> 
> [Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.

**Comment by fippo** [comment]
i don't see either used?!

**Comment by ibc** [comment]
Excuse me, do you imply that I was wrong and those deprecation warnings just happen in my app due to a different JS module such as [howler.js](https://github.com/goldfire/howler.js/issues/863)?

If so you are right :)
