### ISSUE TITLE
Random error in Safari: TypeError: null is not an object (evaluating 'audioContext.createAnalyser')

### ISSUE THREAD

**Issue by ibc** [otalk/hark#38]
Sometimes, not sure why and hard to reproduce (but it happens often,) I get this error in Safari OSX:

```
TypeError: null is not an object (evaluating 'audioContext.createAnalyser')
```

Obviously it happens [here](https://github.com/otalk/hark/blob/master/hark.js#L46), although I cannot understand why that happens. Looking at the code it's clear that `audioContext` is never `null`...

My usage is very simple, I just do this:

```js
this._hark = hark(stream, { play: false });
```

where `stream` is **always** a proper `MediaStream` instance which **always** has an audio track.

**Comment by ibc** [comment]
Wow, not sure if this may be related:

https://stackoverflow.com/questions/45528945/audiocontext-samplerate-returning-null-after-being-read-8-times

> Your audioCtx assignment should be moved outside of drum(), as it will get called every time, eventually throwing an exception since **you can't create more than 6 audio contexts in a document**.

**Comment by ibc** [comment]
However, `hark` just uses one `AudioContext` instance:

```js
// use a single audio context due to hardware limits
var audioContext = null;
```

**Comment by ibc** [comment]
Ok, this seems to happen when navigating back into the web app (single page app, so navigation is managed locally). It seems that, in this case, the JS bundle (which includes `hark`) is loaded again, and  hence, a new `AudioContext` is created. When doing it (navigate back) 5-6 times, the error above happens.

Not sure why it happens. NOTE: In Chrome it also happens that the `hark` library is re-loaded when navigating back. I use `browserify` to build the JS bundle.

**Comment by ibc** [comment]
NOOOO, there is a bug in `hark.js`!!!

It says:

```js
// use a single audio context due to hardware limits
var audioContext = null;
```

but then, within `module.exports = function(stream, options) {` it does:

```js
audioContext = options.audioContext || null,

[...]

//Setup Audio Context
if (!audioContext) {
  audioContext = new audioContextType();
}
```

This is, if no `options.audioContext` is given, `hark` is **always** creating a new `AudioContext`!!!

**Comment by ibc** [comment]
OK, I read in the doc that:

> `audioContext` (optional, default is to create a new context) If you have already created an `AudioContext`, you can pass it to hark to avoid unnecessarily creating more than one.

Well, the problem is that, even calling `stop` on the `hark` instance, the issue described above happens. My diff above fixes it by ensuring that, if no `options.audioContext` is given, just a single `AudioContext` is used.

**Comment by fippo** [comment]
looks like a regression from #29

**Comment by ibc** [comment]
PR submitted: https://github.com/otalk/hark/pull/39
